# https://taskfile.dev

version: '3'

vars:
  AWS_PROFILE: dmartins
  AWS_REGION: ca-central-1
  SSM_TAG: ssm
  CP1_SSM_TAG: cp1
  INSTANCE_CP1:
    sh: aws ec2 describe-instances --no-cli-pager --output text --query 'Reservations[].Instances[].InstanceId' --filters Name=tag:{{.SSM_TAG}},Values={{.CP1_SSM_TAG}} Name=instance-state-name,Values=running

tasks:
  connect-cp1:
    cmds:
      - aws ssm start-session --target {{.INSTANCE_CP1}}
